namespace :db do
  task :populate => :environment do
  	desc "Populating db"

  	puts "Populate start"

  	#Removing data
  	Role.delete_all
  	User.delete_all
  	Lo.delete_all
  	Evmethod.delete_all
  	Assignment.delete_all
  	Evaluation.delete_all

  	#Create Roles
  	role_sadmin = Role.create!  :name  => "SuperAdmin"
  	role_admin = Role.create!  :name  => "Admin"
  	role_reviewer = Role.create!  :name  => "Reviewer"
	role_user = Role.create!  :name  => "User"

	#Create users
	user_admin = User.new
	user_admin.name = "admin"
	user_admin.email = "admin@loep.com"
	user_admin.password = "admin"
	user_admin.password_confirmation = "admin"
	user_admin.lan = "es"
	user_admin.roles.push(role_sadmin)
	user_admin.roles.push(role_admin)
	user_admin.save(:validate => false)

	user_reviewer = User.new
	user_reviewer.name = "reviewer"
	user_reviewer.email = "reviewer@loep.com"
	user_reviewer.password = "reviewer"
	user_reviewer.password_confirmation = "reviewer"
	user_reviewer.lan = "es"
	user_reviewer.roles.push(role_reviewer)
	user_reviewer.save(:validate => false)

	#Create LOs
	loA = Lo.new
	loA.url = "http://vishub.org/excursions/83"
	loA.name = "Curiosity Flashcard"
	loA.description = "A Flashcard about Curiosity, the car-sized robotic rover exploring Gale Crater on Mars."
	loA.lotype = "VE slideshow"
	loA.repository = "ViSH"
	loA.technology = "HTML"
	loA.lan = "en"
	loA.hasQuizzes = true
	loA.save(:validate => false)

	loB = Lo.new
	loB.url = "http://vishub.org/excursions/44"
	loB.name = "Chess: The Art of Learning"
	loB.description = "The Art of Learning, a journey in the pursuit of excellence. Amazing presentation with images, videos and 3d objects, generated by Vish Editor."
	loB.lotype = "VE slideshow"
	loB.repository = "ViSH"
	loB.technology = "HTML"
	loB.lan = "es"
	loB.hasQuizzes = false
	loB.hasWebs = true
	loB.save(:validate => false)

	#Create Evaluation Methods
	LORI = Evmethod.new
	LORI.name = "LORI v1.5"
	LORI.save(:validate => false)

	#Create Assignments

	#Admin create an assigment to request the Reviewer to evaluate the Curiosity Flashcard
	asA = Assignment.new
    asA.author_id = user_admin.id
    asA.user_id = user_reviewer.id
    asA.lo_id = loA.id
	asA.status = "Pending"
	#Deadline in one week
	asA.deadline = DateTime.now + 7
	asA.description = "Please, evaluate the following flashcard using LORI (Learning Object Review Instrument)."
	asA.evmethods.push(LORI)
	asA.save(:validate => false)

	#Also evaluate the LO titled: Chess: The Art of Learning
	#Admin create an assigment to request the Reviewer to evaluate the Curiosity Flashcard
	asB = Assignment.new
    asB.author_id = user_admin.id
    asB.user_id = user_reviewer.id
    asB.lo_id = loB.id
	asB.status = "Pending"
	#Deadline in two weeks
	asB.deadline = DateTime.now + 14
	asB.description = "Please, evaluate the following LO using LORI (Learning Object Review Instrument)."
	asB.evmethods.push(LORI)
	asB.save(:validate => false)

	#Create evaluations
	#Reviewer evaluate the Curiosity Flashcard using LORI (Evaluation requested in the assignment)
	evA = LoriEvaluation.new #Evaluation.new
	evA.user_id = user_reviewer.id
	evA.lo_id = loA.id
	evA.evmethod_id = LORI.id
	evA.assignment_id = asA.id #not mandatory
	evA.save(:validate => false)

	puts "Populate finish"
  end
end